mol new complex.parm7
mol addfile ./0/pull_1.0.restart.coor
mol addfile ./1/pull_1.1.restart.coor
mol addfile ./2/pull_1.2.restart.coor
mol addfile ./3/pull_1.3.restart.coor
mol addfile ./4/pull_1.4.restart.coor
mol addfile ./5/pull_1.5.restart.coor
mol addfile ./6/pull_1.6.restart.coor
mol addfile ./7/pull_1.7.restart.coor
mol addfile ./8/pull_1.8.restart.coor
mol addfile ./9/pull_1.9.restart.coor
